---
language: python
services: docker

env:
  - solr_version: 8.x
    solr_process: solr
  - solr_version: 7.x
    solr_process: solr
  - solr_version: 6.x
    solr_process: solr
  - solr_version: 5.x
    solr_process: solr
  - solr_version: 4.x
    solr_process: solr
  - solr_version: 3.x
    solr_process: start.jar

install:
  # Install Ansible.
  - pip install ansible ansible-lint docker shyaml
  - export ANSIBLE_FORCE_COLOR=true

  # Install role dependencies.
  - ansible-galaxy install -r requirements.yml

script:
  # Check the playbook's syntax.
  - ansible-lint

  # Build the container.
  - ansible-playbook --extra-vars="@vars/${solr_version}.yml" main.yml

  # Get the specific version installed.
  - export exact_version=$(cat vars/${solr_version}.yml | shyaml get-value solr_version)

  # Verify the container runs Solr runs inside.
  - docker run -d --name=solr -p 8983:8983 geerlingguy/solr:${exact_version}
  - >
    docker exec solr ps -ax | grep -q "${solr_process}"
    && (echo 'solr is running: pass' && exit 0)
    || (echo 'solr is running: fail' && exit 1)

after_success:
  - |
    if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      # Log into Docker Hub.
      echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # Push $solr_version tag.
      docker push geerlingguy/solr:${exact_version}

      # Push $solr_version tag.
      docker tag geerlingguy/solr:${exact_version} geerlingguy/solr:${solr_version}
      docker push geerlingguy/solr:${solr_version}

      # Push latest tag if building latest version.
      if [[ "$solr_version" == "8.x" ]]; then
        docker tag geerlingguy/solr:${exact_version} geerlingguy/solr:latest
        docker push geerlingguy/solr:latest
      fi
    fi
