---
language: python
services: docker

env:
  - solr_version: '7.x'
  - solr_version: '6.x'
  - solr_version: '5.x'
  - solr_version: '4.x'
  - solr_version: '3.x'

install:
  # Install Ansible.
  - pip install ansible docker shyaml

  # Install role dependencies.
  - ansible-galaxy install -r requirements.yml

script:
  # Build the container.
  - ansible-playbook --extra-vars="@vars/${solr_version}.yml" main.yml

  # Get the specific version installed.
  - export exact_version=$(cat vars/${solr_version}.yml | shyaml get-value solr_version)

  # Verify the container runs Solr runs inside.
  - docker run -d --name=solr -p 8080:80 geerlingguy/solr:${exact_version}
  - >
    docker exec solr ps -ax | grep -q 'solr'
    && (echo 'solr is running: pass' && exit 0)
    || (echo 'solr is running: fail' && exit 1)
